/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author Luciana Vieira
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSenha = new javax.swing.JLabel();
        btnlogin = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        btnacessar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSenha.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSenha.setForeground(new java.awt.Color(51, 153, 0));
        btnSenha.setText("Senha:");
        getContentPane().add(btnSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        btnlogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(51, 153, 0));
        btnlogin.setText("Login:");
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 90, -1));
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, -1));

        btnacessar.setText("Acessar");
        btnacessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacessarActionPerformed(evt);
            }
        });
        getContentPane().add(btnacessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        btnsair.setText("Sair");
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        btncadastrar.setText("Cadastrar-se");
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/pilfisioterapia-01.jpg"))); // NOI18N
        getContentPane().add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnacessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacessarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnacessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSenha;
    private javax.swing.JButton btnacessar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JLabel btnlogin;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel imagem;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
